src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EleveRepository::class)
 */
class Eleve extends Personne
{

    /**
     * @ORM\ManyToOne(targetEntity=Groupe::class, inversedBy="eleves")
     * @ORM\JoinColumn(nullable=false)
     */
    private $groupe;

    /**
     * @ORM\OneToMany(targetEntity=Absence::class, mappedBy="absent", orphanRemoval=true)
     */
    private $absences;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="eleve", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        parent::__construct();
        $this->absences = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getRoles(): array
    {
        $roles = parent::getRoles();
        $roles[] = 'ROLE_ELEVE';
        return array_unique($roles);
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    /**
     * @return Collection|Absence[]
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setAbsent($this);
        }

        return $this;
    }

    public function removeAbsence(Absence $absence): self
    {
        if ($this->absences->contains($absence)) {
            $this->absences->removeElement($absence);
            // set the owning side to null (unless already changed)
            if ($absence->getAbsent() === $this) {
                $absence->setAbsent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setEleve($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getEleve() === $this) {
                $note->setEleve(null);
            }
        }

        return $this;
    }

    public function getItems(): array
    {
        $items = parent::getItems();
        $items_child = [
            "Notes" => "eleve_notes",
            "Absences" => "eleve_absences"
        ];

        if (empty($items))
            return $items_child;
        else
            return array_merge($items, $items_child);
    }

}

src/Entity/Examen.php
<?php

namespace App\Entity;

use App\Repository\ExamenRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ExamenRepository::class)
 */
class Examen extends Cours
{

    /**
     * @ORM\Column(type="float")
     * @Assert\PositiveOrZero
     */
    private $coefficient;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive
     */
    private $note_max;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="examen", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        parent::__construct();
        $this->notes = new ArrayCollection();
        $this->note_max = 20;
        $this->coefficient = 1;
    }

    public function getCoefficient(): ?float
    {
        return $this->coefficient;
    }

    public function setCoefficient(float $coefficient): self
    {
        $this->coefficient = $coefficient;

        return $this;
    }

    public function getNoteMax(): ?float
    {
        return $this->note_max;
    }

    public function setNoteMax(float $note_max): self
    {
        $this->note_max = $note_max;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setExamen($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getExamen() === $this) {
                $note->setExamen(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return strval($this->getMatiere() . " - Note sur " . $this->getNoteMax() . " - Coefficient " . $this->getCoefficient());
    }
}

src/Entity/Note.php
<?php

namespace App\Entity;

use App\Repository\NoteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=NoteRepository::class)
 * @UniqueEntity(
 *     fields={"eleve", "examen"},
 *     errorPath="eleve",
 *     message="Une note a déjà attribuée à cet élève pour cet examen."
 * )
 */
class Note
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     * @Assert\PositiveOrZero
     * @Assert\LessThanOrEqual(propertyPath="examen.note_max")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity=Eleve::class, inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $eleve;

    /**
     * @ORM\ManyToOne(targetEntity=Examen::class, inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $examen;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(float $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }

    public function getExamen(): ?Examen
    {
        return $this->examen;
    }

    public function setExamen(?Examen $examen): self
    {
        $this->examen = $examen;

        return $this;
    }

    public function __toString()
    {
        return strval($this->getId());
    }
}

src/Controller/EleveController.php
<?php

namespace App\Controller;

use App\Form\EleveAbsenceType;
use App\Form\EleveProfileType;
use App\Form\ResetPasswordType;
use App\Repository\AbsenceRepository;
use App\Repository\MatiereRepository;
use App\Repository\NoteRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * Class EleveController
 * @package App\Controller
 * @Route("/eleve", name="eleve")
 * @IsGranted("ROLE_ELEVE")
 */
class EleveController extends AbstractController
{
    /**
     * @Route("/settings", name="_settings", methods={"GET","POST"})
     */
    public function edit(Request $request, UserPasswordEncoderInterface $encoder): Response
    {
        $eleve = $this->getUser();
        $form = $this->createForm(EleveProfileType::class, $eleve);
        $form->handleRequest($request);
        $form_rp = $this->createForm(ResetPasswordType::class, $eleve);
        $form_rp->handleRequest($request);
        if ($form_rp->isSubmitted() && $form_rp->isValid()) {
            $newEncodedPassword = $encoder->encodePassword($eleve, $eleve->getPlainPassword());
            $eleve->setPassword($newEncodedPassword);
            $this->getDoctrine()->getManager()->persist($eleve);
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('notice', 'Votre mot de passe à bien été changé !');
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
        }

        return $this->render('eleve/edit.html.twig', [
            'form' => $form->createView(),
            'form_rp' => $form_rp->createView()
        ]);
    }

    /**
     * @Route("/notes", name="_notes")
     */
    public function indexNote(NoteRepository $noteRepository, MatiereRepository $matiereRepository): Response
    {
        $eleve = $this->getUser();
        $notes = $eleve->getNotes();
        $moyennes = array();
        $matieres = $matiereRepository->findAll();
        foreach ($matieres as $matiere) {
            $moyenne = $noteRepository->getMoyenne($eleve, $matiere);
            $moyennes[$matiere->getIntitule()] = $moyenne[0]["1"];
        }

        return $this->render('eleve/note/index.html.twig', [
                "moyennes" => $moyennes,
                "notes" => $notes
            ]
        );
    }

    /**
     * @Route("/note/{id}", name="_note")
     */
    public function showNote(Request $request, NoteRepository $noteRepository): Response
    {
        $id = $request->get("id");
        $note = $noteRepository->findOneBy([
            "eleve" => $this->getUser(),
            "id" => $id
        ]);

        if ($note) {
            return $this->render("eleve/note/show.html.twig", [
                "note" => $note
            ]);
        } else {
            return $this->redirectToRoute("eleve_notes");
        }
    }

    /**
     * @Route("/absences", name="_absences")
     */
    public function indexAbsence()
    {
        $eleve = $this->getUser();
        $absences = $eleve->getAbsences()->filter(
            function ($absence) {
                return $absence->getCours()->getStatut();
            }
        );

        return $this->render("eleve/absence/index.html.twig", [
                "absences" => $absences
            ]
        );
    }

    /**
     * @Route("/absence/{id}/edit", name="_absence_edit")
     */
    public function editAbsence(Request $request, AbsenceRepository $absenceRepository): Response
    {
        $id = $request->get("id");
        $absence = $absenceRepository->findOneBy([
            "absent" => $this->getUser(),
            "id" => $id
        ]);

        if ($absence) {
            $form = $this->createForm(EleveAbsenceType::class, $absence);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $absence = $form->getData();
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($absence);
                $entityManager->flush();
                return $this->redirectToRoute("eleve_absences");
            }

            return $this->render("eleve/absence/edit.html.twig", [
                'form' => $form->createView(),
                "absence" => $absence
            ]);
        } else {
            return $this->redirectToRoute("eleve_absences");
        }
    }
}

templates/eleve/note/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notes de {{ app.user.prenom|capitalize ~ " " ~ app.user.nom|upper }}{% endblock %}
{% block body %}
    {% embed "user/_navbar.html.twig" %}
    {% endembed %}
    {% embed "user/_container.html.twig" %}
        {% block container %}

            {% embed "user/_card.html.twig" with {card_header:1} %}
                {% block header %}<b>Notes de {{ app.user.prenom|capitalize ~ " " ~ app.user.nom|upper }}</b>
                {% endblock %}
                {% block text %}
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Matière</th>
                                <th>Professeur</th>
                                <th>Note</th>
                                <th>Coefficient</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for note in notes %}
                                <tr>
                                    <td>{{ note.examen.matiere.intitule }}</td>
                                    <td>{{ note.examen.professeur.prenom|capitalize ~ " " ~ note.examen.professeur.nom|upper }}</td>
                                    <td>{{ note.note ~ " / " ~ note.examen.noteMax }}</td>
                                    <td>{{ note.examen.coefficient }}</td>
                                    <td><a href="{{ path("eleve_note", {id: note.id}) }}">Afficher note</a></td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5">Pas de note</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <hr>
                    <h3>Moyennes</h3>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Matière</th>
                                <th>Moyenne</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for matiere,moyenne in moyennes %}
                                <tr>
                                    <td>{{ matiere }}</td>
                                    <td>{{ moyenne|round(1, 'floor') }}</td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5">Pas de moyennes</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <a class="btn btn-warning" href="{{ path("personne_index") }}">Retourner à l'accueil</a>
                {% endblock %}
            {% endembed %}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/eleve/note/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Note n°{{ note.id }}{% endblock %}
{% block body %}
    {% embed "user/_navbar.html.twig" %}
    {% endembed %}
    {% embed "user/_container.html.twig" %}
        {% block container %}
            {% embed "user/_card.html.twig" with {card_header:1} %}
                {% block header %}<b>
                    Note n°{{ note.id }}
                    </b>
                {% endblock %}
                {% block text %}
                    <h5><u>Note de {{ note.examen.matiere.intitule }} </u></h5>
                    Noté par : <b>{{ note.examen.professeur.prenom|capitalize }} {{ note.examen.professeur.nom|upper }}</b><br>
                    <br>
                    <b>Résultat :</b>
                    <p>{{ note.note ~ " / " ~ note.examen.noteMax }}</p>

                    <a class="btn btn-warning mt-2" href="{{ path("eleve_notes") }}">Retour aux notes</a>
                {% endblock %}
            {% endembed %}
        {% endblock %}
    {% endembed %}
{% endblock %}