src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity(
 *     fields={"username"},
 *     errorPath="username",
 *     message="Un utilisateur de ce nom existe déjà."
 * )
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type",type="string")
 * @ORM\DiscriminatorMap({
 *     "personne" = "Personne",
 *     "admin" = "Administrateur",
 *     "eleve" = "Eleve",
 *     "prof" = "Professeur"
 * })
 * @Vich\Uploadable
 */
abstract class Utilisateur implements UserInterface, Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Length(min="6")
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="6")
     */
    private $password;

    /**
     * @var string the plain password (local)
     */
    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_picture_path;

    /**
     * @Vich\UploadableField(mapping="personne_profile_pictures", fileNameProperty="profile_picture_path")
     * @var File
     */
    private $profile_picture_file;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function __toString()
    {
        return strval($this->username);
    }

    /**
     * @return string
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     * @return Utilisateur
     */
    public function setPlainPassword(string $plainPassword): Utilisateur
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    /**
     * @return File
     */
    public function getProfilePictureFile()
    {
        return $this->profile_picture_file;
    }

    /**
     * @param File $profile_picture_file
     * @return $this
     */
    public function setProfilePictureFile(?File $profile_picture_file = null): self
    {
        $this->profile_picture_file = $profile_picture_file;
        if (null !== $profile_picture_file) {
            $this->updatedAt = new DateTimeImmutable();
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getProfilePicturePath(): ?string
    {
        return $this->profile_picture_path;
    }

    /**
     * @param $profile_picture
     * @return $this
     */
    public function setProfilePicturePath($profile_picture): self
    {
        $this->profile_picture_path = $profile_picture;

        return $this;
    }

    public function getAvatarUri(): ?string
    {
        if ($this->getProfilePicturePath()) {
            return "/uploads/images/profile_pictures/" . $this->getProfilePicturePath();
        } else {
            return null;
        }
    }

    public function serialize()
    {
        $this->profile_picture_file = base64_encode($this->profile_picture_file);
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->profile_picture_path,
            $this->profile_picture_file
        ));
    }

    public function unserialize($serialized)
    {
        $this->profile_picture_file = base64_decode($this->profile_picture_file);
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->profile_picture_path,
            $this->profile_picture_file
            ) = unserialize($serialized);
    }

    public function getDropdowns(): array
    {
        return [];
    }

    public function getItems(): array
    {
        return [];
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }


}

templates/user/_card.html.twig
<div class="card mt-2 shadow {{ card_classes|default("") }}">
    {% if card_header is defined %}
        <h5 class="card-header">{% block header %}Header{% endblock %}</h5>
    {% endif %}
    <div class="card-body">
        {% if card_title is defined %}
            <h5 class="card-title">{% block title %}Title{% endblock %}</h5>
        {% endif %}
        <h6 class="card-subtitle mb-2 text-muted"></h6>
        <p class="card-text">
            {% block text %}
                Texte
            {% endblock %}
        </p>
    </div>
</div>

templates/user/_collapse.html.twig
<div class="card {{ color|default("bg-light") }}"
     {% if color_css is defined %}style="background-color: {{ color_css }}"{% endif %}>
    <div class="card-header" id="heading_{{ id }}">
        <h5 class="mb-0">
            <button class="btn collapsed {{ color_btn|default }}" type="button" data-toggle="collapse" data-target="#collapse_{{ id }}"
                    aria-expanded="true" aria-controls="collapse_{{ id }}">
                {% block button %}Bouton{% endblock %}
            </button>
        </h5>
    </div>

    <div id="collapse_{{ id }}" class="collapse " aria-labelledby="heading_{{ id }}"
         data-parent="#{{ parent|default("") }}">
        <div class="card-body">
            {% block text %}Texte{% endblock %}
        </div>
    </div>
</div>

templates/user/_container.html.twig
<div class="container my-3">
    {% block container %}
    {% endblock %}
</div>

templates/user/_container_fluid.html.twig
<div class="container-fluid my-3">
    {% block container_fluid %}
    {% endblock %}
</div>

templates/user/_navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <a class="navbar-brand" href="{{ path('security_post_login') }}">{% block nav_brand %}<i
                class="fas fa-compass"></i>{% endblock %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% block nav_items %}
                {% for name,route in app.user.items %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path(route) }}">{{ name }}</a>
                    </li>
                {% endfor %}
                {% for name,items in app.user.dropdowns %}
                    {% set id = random() %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown{{ id }}" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown{{ id }}">
                            {% for item,route in items %}
                                <a class="dropdown-item" href="{{ path(route) }}">{{ item }}</a>
                            {% endfor %}
                        </div>
                    </li>
                {% endfor %}
            {% endblock %}
        </ul>
        {% if not app.user.profilePicturePath is null %}
            {% set image = get_param("profile_pictures") ~ asset(app.user.profilePicturePath) %}
        {% else %}
            {% set image = asset("uploads/images/profile_pictures/user-circle.svg") %}
        {% endif %}
        {% if is_granted('ROLE_ELEVE') %}
            {% set path = path("eleve_settings") %}
        {% elseif is_granted("ROLE_PROF") %}
            {% set path = path("prof_settings") %}
        {% endif %}
        <span class="mx-lg-2 mx-0">
            <a class="text-muted nav-link p-1" href="{{ path }}">
                <i class="fas fa-cog"></i>
                {{ app.user.prenom|capitalize ~ " " ~ app.user.nom|upper }}
                <img src="{{ image|imagine_filter("my_fixed_filter") }}"
                     alt="userpic"
                     class="rounded-circle mx-1 shadow-lg"
                     style="width: 2rem; vertical-align: -10px">
            </a>
        </span>

        <form class="form-inline" action="{{ path('security_logout') }}">
            <button class="btn btn-danger my-sm-0" type="submit">Logout</button>
        </form>
    </div>
</nav>

{% block javascripts %}
    <script src="https://kit.fontawesome.com/03b0271aa1.js" crossorigin="anonymous"></script>
{% endblock %}

templates/user/_reset_password.html.twig
{{ form_start(form_rp) }}
    {{ form_widget(form_rp) }}
<button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form_rp) }}